// Generated by SolidPython 1.1.3 on 2025-05-14 21:59:40


cube(center = true, size = [100, 50, 20]);
/***********************************************
*********      SolidPython code:      **********
************************************************
 
from solid import *
from solid.utils import *

c = cube([100, 50, 20], center=True)

scad_render_to_file(c, "sample.scad")
 
 
************************************************/
